### ISSUE TITLE
number of cells

### ISSUE THREAD

**Issue by cartographerJ** [TileDB-Inc/tiledbsc#43]
Thanks for making this implementation! I am curious how many cells this can handle; I am hitting a character vector limit with less than 1 million cells. 

```Creating new AssayMatrix array with index [var_id,obs_id] at './aml_test/scgroup_RNA/X/counts'
Ingesting assay data into ./test/scgroup_RNA/X/counts
Error in paste(txtvec, collapse = "") : result would exceed 2^31-1 bytes
In addition: Warning message:
In `[<-`(`*tmp*`, , value = list(var_id = c("SDF4", "CDK11B", "GNB1",  :
  integer overflow in 'cumsum'; use 'cumsum(as.numeric(.))```

**Comment by eddelbuettel** [comment]
Hi @cartographerJ and thanks for taking the time to report this.  @aaronwolen poked me on this as this is likely something in the underlying TileDB R package I am working on.   Would you be able to describe (or even provide ?) a mock data set reproducing this?  

(The underlying reason is that internally we represent string vectors as on very long string with a vector of offsets.  And as the error you kindly quote shows, we do pivot from `int` to `numeric` -- but it looks I start the vector with an explicit `0L` (line 1116 [here](https://github.com/TileDB-Inc/TileDB-R/blob/338945edbe21bbcd29c7a052a60b9cc1f1e4b8e9/R/TileDBArray.R#L1115-L1117) which may bring limited integers back in.  It may be something we can fix quickly, but reproducing it first would likely be of help.)

**Comment by cartographerJ** [comment]
The data I was using I can't share - but this seems to recapitulate the same error (I haven't tested how many cells will trigger the error so this may be overkill)

```
require(tidyverse)
require(Seurat)
require(SeuratData)
require(tiledbsc)

# get decent sized data
InstallData("hcabm40k")
data("hcabm40k")
hcabm40k

# replicate into bigger data 40k->400k
l <- list()
for(i in 1:10){
    l[[i]] <- hcabm40k
}
names(l) <- paste0("fake_", 1:10)
big <- merge(l[[1]], l[2:10])

# test if will crash the tiledb implementation
scdataset <- SCDataset$new(uri = file.path(".", "hcabm40k_test"))
scdataset$from_seurat(object = big)
```

**Comment by eddelbuettel** [comment]
Nice example which almost brought my machine to its knees :)   @aaronwolen was of great help and distilled an equivalent example out of `Seurat` and its data (and we have the rds file in an s3 bucket) which I extended a little to cache with `fst`

```r
library(Matrix)
library(tools)
library(tiledb)
library(fst)

rdsfile <- "hcabm40k_rna_counts.rds"
uri <- file_path_sans_ext(rdsfile)
fstfile <- paste0(uri, ".fst")

if (!dir.exists(fstfile)) {
    mat <- as(readRDS(rdsfile), "dgTMatrix")
    df <- data.frame(i = mat@i + 1L, j = mat@j + 1L, x = mat@x)
    df$i <- rownames(mat)[df$i]
    df$j <- colnames(mat)[df$j]
    write_fst(df, fstfile)
} else {
    df <- read_fst(fstfile)
}

if (tiledb_vfs_is_dir(uri)) tiledb_vfs_remove_dir(uri)
fromDataFrame(df, uri = uri, col_index = c("i", "j"))
```

In creating dimensions (or attributes) from string vectors, we returned two intermediate vectors back to R which makes the R constraint on vector size binding.  And that becomes in issue in a data set this large.  

A fix (which successfully ingested the 140 million data.frame from the code snippet above which otherwise throws the same error in the current release) is now in [this branch](https://github.com/TileDB-Inc/TileDB-R/tree/de/sc-16919/large_char_vec) from where you could install it if you needed the update urgently.   I am also now running your longer example but it also rather large and forced the EC2 instance I used into swapping a little so it may be a moment until I can confirm that it completes the task (which I expect it too, it has been running for a few hours already whereas error condition reveals itself much more promptly).

Otherwise I expect this to be reviewed and merged within a (business) day or two; as we just uploaded to CRAN it may take a little longer to make it to the published package there.   Please let us know if you'd need help with particular builds (`conda` or alike) for which we may able to assist.

**Comment by eddelbuettel** [comment]
Thanks again for reporting the issue. The non-merrged [PR #400 in the TileDB-R repo](https://github.com/TileDB-Inc/TileDB-R/pull/400) addresses this.  

Please let us know if you need any help getting a binary, or if you notice any other issues.
